services:
  - type: web
    name: laravel-api
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    buildCommand: "composer install && php artisan migrate --force && php artisan storage:link && php artisan cache:clear && php artisan route:cache"
    startCommand: "sh start.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        scope: run_and_build
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d5pn013uibrs73d4gcf0-a.oregon-postgres.render.com
        scope: run_and_build
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: laravel_n2m1
        scope: run_and_build
        sync: false
      - key: DB_USERNAME
        value: laravel
        scope: run_and_build
        sync: false
      - key: DB_PASSWORD
        scope: run_and_build
        sync: false
